"""
Broker Protocol — the interface all broker adapters must implement.

No order-placement code may bypass this interface.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Protocol, runtime_checkable

from .types import Account, Fill, Order, OrderAck, Position, Quote


@runtime_checkable
class Broker(Protocol):
    def account(self) -> Account: ...
    def positions(self) -> dict[str, Position]: ...
    def quote(self, symbol: str) -> Quote: ...
    def submit(self, order: Order) -> OrderAck: ...
    def cancel(self, order_id: str) -> None: ...
    def open_orders(self) -> list[Order]: ...
    def fills_since(self, ts: datetime) -> list[Fill]: ...
    def env(self) -> Literal["paper", "live"]: ...
